//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorvinMozi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CorvinMozi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap balnyil {
            get {
                object obj = ResourceManager.GetObject("balnyil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korda Sándor
        ///8;10
        ///5;5;F
        ///4;5;F
        ///3;5;D
        ///2;1;D
        ///4;1;D
        ///4;1;F
        ///6;2;D
        ///7;6;D
        ///8;9;D
        ///1;10;D
        ///2;10;D
        ///8;6;F
        ///3;10;F
        ///1;4;D
        ///2;6;D
        ///8;3;F
        ///4;5;D
        ///6;10;F
        ///2;3;F
        ///5;8;F
        ///3;8;D
        ///7;2;F
        ///5;2;D
        ///7;3;D
        ///6;10;F
        ///6;1;F
        ///5;7;D
        ///5;5;F
        ///4;8;D
        ///1;7;F
        ///7;3;D
        ///3;1;F
        ///7;1;D
        ///5;5;F
        ///1;1;D
        ///7;9;F
        ///4;4;D
        ///7;8;F
        ///6;3;D
        ///4;9;D
        ///8;6;D
        ///8;3;D
        ///5;1;F
        ///4;1;D
        ///4;5;F
        ///2;5;D
        ///2;3;F
        ///3;4;F
        ///1;2;F
        ///4;9;D
        ///8;8;F
        ///2;8;D
        ///6;8;F
        ///1;9;D
        ///2;5;D
        ///5;5;F
        ///7;3;F
        ///8;10;D
        ///5;8;D
        ///6;4;D
        ///2;1;D
        ///4;8;D
        ///2;6;F
        ///4;3;F
        ///5;7;D
        ///3;9;D
        ///3;1;D
        ///3;8;D
        ///1;8;F
        ///2;4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CorvinMozi {
            get {
                return ResourceManager.GetString("CorvinMozi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap felnott {
            get {
                object obj = ResourceManager.GetObject("felnott", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gyerek {
            get {
                object obj = ResourceManager.GetObject("gyerek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jávor {
            get {
                object obj = ResourceManager.GetObject("Jávor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jobbra {
            get {
                object obj = ResourceManager.GetObject("jobbra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kabos {
            get {
                object obj = ResourceManager.GetObject("Kabos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Karády {
            get {
                object obj = ResourceManager.GetObject("Karády", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Korda {
            get {
                object obj = ResourceManager.GetObject("Korda", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Latabár {
            get {
                object obj = ResourceManager.GetObject("Latabár", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Radványi {
            get {
                object obj = ResourceManager.GetObject("Radványi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ures {
            get {
                object obj = ResourceManager.GetObject("ures", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
